src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 */
class Property
{
    const HEAT = [
        0 => "Electric",
        1 => "Solar",
        3 => "Petrol",
        4 => "Gaz"
    ];
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=25)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;
    
    public function __construct() {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
    
    public function getSlug(): string
    {
        $slugify = new Slugify();
        return $slugify->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }
    
    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(?int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }
    
    public function heatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(?string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }
    
    private function getChoices(): array
    {
        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $k => $v)
        {
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Property;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;

/**
 * @Route("/proprietes", name="property_")
 */
class PropertyController extends AbstractController
{
    /**
     * @var PropertyRepository
     */
    private $repository;

    /**
     * @var EntityManagerInterface
     */
    private $entityManager;
    
    public function __construct(PropertyRepository $repository, EntityManagerInterface $entityManager)
    {
        $this->repository = $repository;
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/", name="home")
     */
    public function home(): Response
    {
        $properties = $this->repository->findAllVisible();
        return $this->render('property/home.html.twig');
    }

    /**
     * @Route("/{slug}-{id}", name="show", requirements={"slug": "[a-z0-9\-]*"})
     */
    public function show(Property $property, $slug): Response
    {
        if($slug !== $property->getSlug()){
            return $this->redirectToRoute("property_show", [
                "id" => $property->getId(),
                "slug" => $property->getSlug()
            ], 301);
        }
        return $this->render('property/show.html.twig', [
            "property" => $property
        ]);
    }
}

templates/property/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Property{% endblock %}

{% block body %}
    <div class="container my-5">
        <h1 class="text-center">All properties</h1>
        <!-- Three Column Section -->
        <div class="container elements">
            <div class="row my-5">

                <div class="col-md-4 col-sm-6 col-xs-12 my-4">
                    <img src="/img/2.jpg" class="w-100">
                    <h4 class="my-4">Home</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua.</p>
                    <p class="d-flex justify-content-between">
                        <a href="#" class="btn btn-outline-dark btn-md">Detail</a>
                        <a href="#" class="btn btn-outline-dark btn-md">300£</a>
                    </p>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12 my-4">
                    <img src="/img/3.jpg" class="w-100">
                    <h4 class="my-4">Home</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua.</p>
                    <p class="d-flex justify-content-between">
                        <a href="#" class="btn btn-outline-dark btn-md">Detail</a>
                        <a href="#" class="btn btn-outline-dark btn-md">300£</a>
                    </p>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12 my-4">
                    <img src="/img/1.jpg" class="w-100">
                    <h4 class="my-4">Home</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua.</p>
                    <p class="d-flex justify-content-between">
                        <a href="#" class="btn btn-outline-dark btn-md">Detail</a>
                        <a href="#" class="btn btn-outline-dark btn-md">300£</a>
                    </p>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12 my-4">
                    <img src="/img/3.jpg" class="w-100">
                    <h4 class="my-4">Home</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua.</p>
                    <p class="d-flex justify-content-between">
                        <a href="#" class="btn btn-outline-dark btn-md">Detail</a>
                        <a href="#" class="btn btn-outline-dark btn-md">300£</a>
                    </p>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12 my-4">
                    <img src="/img/1.jpg" class="w-100">
                    <h4 class="my-4">Home</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua.</p>
                    <p class="d-flex justify-content-between">
                        <a href="#" class="btn btn-outline-dark btn-md">Detail</a>
                        <a href="#" class="btn btn-outline-dark btn-md">300£</a>
                    </p>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12 my-4">
                    <img src="/img/2.jpg" class="w-100">
                    <h4 class="my-4">Home</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua.</p>
                    <p class="d-flex justify-content-between">
                        <a href="#" class="btn btn-outline-dark btn-md">Detail</a>
                        <a href="#" class="btn btn-outline-dark btn-md">300£</a>
                    </p>
                </div>

            </div>
        </div>


	<!-- Start Footer -->

	<!-- End Footer -->


	<!-- Start Socket -->

	<!-- End Socket -->
    </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    
    <!-- Detail -->
    <div class="detail">
        <h1 class="text-center my-5">{{ property.title }}</h1>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4 my-2 text-center">
                    <h2 class="mb-3">Description</h2>
                    <p>
                        {{ property.description | nl2br}}
                    </p>
                    <p>
                        {{ property.rooms }} pieces - {{ property.surface }} m²
                    </p>
                    <h3><a href="#" class="btn btn-outline-dark">Contacter l'agence</a></h3>
                </div>
                <div class="col-md-4 my-2">
                    <img src="/img/2.jpg" class="w-100">
                </div>
                <div class="col-md-4 my-2 d-flex align-self-center justify-content-end">
                    <h3>Price : <strong>{{ property.formattedPrice }} £</strong></h3>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-md-8">
                    <h1>Features</h1>
                    <table class="table table-striped">
                        <tr>
                            <td>Surface</td>
                            <td>{{ property.surface }}</td>
                        </tr>
                        <tr>
                            <td>Pieces</td>
                            <td>{{ property.rooms }}</td>
                        </tr>
                        <tr>
                            <td>Bedrooms</td>
                            <td>{{ property.bedrooms }}</td>
                        </tr>
                        <tr>
                            <td>Floor</td>
                            <td>{{ property.floor }}</td>
                        </tr>
                        <tr>
                            <td>Heat</td>
                            <td>{{ property.heatType }}</td>
                        </tr>
                        <tr>
                            <td>Surface</td>
                            <td>{{ property.surface }}</td>
                        </tr>
                    </table>
                </div>
                <div class="col-md-4">
                    <h2>Specificities</h2>
                </div>
            </div>
        </div>
    </div>
    <!-- Detail end -->

    <!-- Suggestion -->
    <div class="container-fluid elements mt-5">
        <div class="row">
            <div class="col-md-12">
                <div class="text-center">
                    <p>Suggestions</p>
                </div>
            </div>
        </div>

        <div class="row my-5">

            <div class="col-md-4 col-sm-6 col-xs-12 my-4">
                <img src="/img/1.jpg" class="w-100">
                <h4 class="my-4">Home</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua.</p>
                <p class="d-flex justify-content-between">
                    <a href="detail.html" class="btn btn-outline-dark btn-md">Détail</a>
                    <a href="detail.html" class="btn btn-outline-dark btn-md">Price</a>
                </p>
            </div>



            <div class="col-md-4 col-sm-6 col-xs-12 my-4">
                <img src="/img/2.jpg" class="w-100">
                <h4 class="my-4">Home</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua.</p>
                <p class="d-flex justify-content-between">
                    <a href="index.html" class="btn btn-outline-dark btn-md">Détail</a>
                    <a href="index.html" class="btn btn-outline-dark btn-md">Price</a>
                </p>
            </div>


            <div class="col-md-4 col-sm-6 col-xs-12 my-4">
                <img src="/img/3.jpg" class="w-100">
                <h4 class="my-4">Home</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua.</p>
                <p class="d-flex justify-content-between">
                    <a href="index.html" class="btn btn-outline-dark btn-md">Détail</a>
                    <a href="index.html" class="btn btn-outline-dark btn-md">Price</a>
                </p>
            </div>

        </div>
    </div>
    <!-- Suggestion end -->

{% endblock %}